name: CI Build

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.sys.os }}
    strategy:
      matrix:
        sys:
          - { os: windows-latest, shell: pwsh }
          - { os: ubuntu-latest,  shell: bash }

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCI_BUILD=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Release
      uses: ncipollo/release-action@a8aa04e74a11445773cf6821f9c8d2a5b317cb1f
      with:
        name: ${{ github.ref }}
        tag: 'unstable'
        artifacts: build/psarc-cl/psarc-cl*
        allowUpdates: false
        omitBodyDuringUpdate: false
        omitDraftDuringUpdate: false
        omitNameDuringUpdate: false
        omitPrereleaseDuringUpdate: false
        prerelease: true
        replacesArtifacts: true
        skipIfReleaseExists: false
