name: Release Build

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.sys.os }}
    strategy:
      matrix:
        sys:
          - { os: windows-latest, shell: pwsh }
          - { os: ubuntu-latest,  shell: bash }

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCI_BUILD=ON -DPSARC_CL_RELEASE_BUILD_VERSION=${{ github.ref }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Release
      uses: ncipollo/release-action@a8aa04e74a11445773cf6821f9c8d2a5b317cb1f
      with:
        name: ${{ github.ref }}
        tag: ${{ github.ref }}
        artifacts: ${{ matrix.shell == 'bash' && 'build/psarc-cl/psarc-cl' || 'build/psarc-cl/Release/psarc-cl.exe' }}
        allowUpdates: true
        draft: true
        omitBodyDuringUpdate: false
        omitDraftDuringUpdate: false
        omitNameDuringUpdate: false
        omitPrereleaseDuringUpdate: false
        replacesArtifacts: false
        skipIfReleaseExists: true
